name: Build and Deploy

on:
  push:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'ap-northeast-1'
      S3_BUCKET_NAME: 's3://'
      BUILD_DIR: dist
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1 # 鎖定到具體版本

      - name: Set timezone to Asia/Taipei
        uses: szenius/set-timezone@v1.2 # 這個 action 比較單純，主版號即可
        with:
          timezoneLinux: "Asia/Taipei"

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4.0.2 # 鎖定到具體版本
        with:
          node-version: '20.x'
          cache: 'npm' # 啟用 npm 快取

      - name: Install npm dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Deploy 到 S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: ${{ secrets.BUILD_DIR }}
